# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6eadc0416a2153f48d168f50cadcbade413355616ba274522072dcc1f2d43d98449abae37bacf808781506c3956bb19b7248b03af12e92cbce9b2b8c40c7a497

test:
  secret_key_base: c1343fef6b85061e1be7aa9e5973c29e931a2d859f40b3705a0ac760a4792b4d6260fefcd96be9ca8d97318836d1d1dcaa00160d8e92f8cd2b2827703e9a2487

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
